/* ─── Curated multilingual quote library ─────────────────────────────── */

export const SUPPORTED_LANGUAGES = [
  { code: 'en', label: 'English',        native: 'English',    rtl: false },
  { code: 'ar', label: 'Arabic',         native: 'العربية',     rtl: true  },
  { code: 'es', label: 'Spanish',        native: 'Español',    rtl: false },
  { code: 'fr', label: 'French',         native: 'Français',   rtl: false },
];

export const QUOTES = {
  en: [
    { text: "Every day is a new beginning. Take a deep breath and start again.", author: "Unknown" },
    { text: "The sun will rise and we will try again.", author: "Twenty One Pilots" },
    { text: "Even the darkest night will end and the sun will rise.", author: "Victor Hugo" },
    { text: "After every storm there is a golden sky.", author: "Bill Shankly" },
    { text: "Wherever you go, go with all your heart.", author: "Confucius" },
    { text: "Life is not about waiting for the storm to pass, but learning to dance in the rain.", author: "Vivian Greene" },
    { text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
    { text: "Happiness is not something ready-made. It comes from your own actions.", author: "Dalai Lama" },
    { text: "In the middle of every difficulty lies opportunity.", author: "Albert Einstein" },
    { text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
    { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { text: "It always seems impossible until it's done.", author: "Nelson Mandela" },
    { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
    { text: "Keep your face always toward the sunshine, and shadows will fall behind you.", author: "Walt Whitman" },
    { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
    { text: "Whether you think you can or you think you can't, you're right.", author: "Henry Ford" },
    { text: "The only impossible journey is the one you never begin.", author: "Tony Robbins" },
    { text: "A year from now you may wish you had started today.", author: "Karen Lamb" },
    { text: "Do not wait to strike till the iron is hot, but make it hot by striking.", author: "William Butler Yeats" },
    { text: "Well done is better than well said.", author: "Benjamin Franklin" },
    { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
    { text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },
    { text: "Life is what happens when you're busy making other plans.", author: "John Lennon" },
    { text: "Spread love everywhere you go. Let no one ever come to you without leaving happier.", author: "Mother Teresa" },
    { text: "What you get by achieving your goals is not as important as what you become by achieving them.", author: "Zig Ziglar" },
    { text: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
    { text: "The journey of a thousand miles begins with a single step.", author: "Lao Tzu" },
    { text: "Be yourself; everyone else is already taken.", author: "Oscar Wilde" },
    { text: "Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.", author: "Albert Einstein" },
    { text: "Be the change that you wish to see in the world.", author: "Mahatma Gandhi" },
    { text: "If you tell the truth, you don't have to remember anything.", author: "Mark Twain" },
    { text: "A friend is someone who knows all about you and still loves you.", author: "Elbert Hubbard" },
    { text: "Always forgive your enemies; nothing annoys them so much.", author: "Oscar Wilde" },
    { text: "We accept the love we think we deserve.", author: "Stephen Chbosky" },
    { text: "Without music, life would be a mistake.", author: "Friedrich Nietzsche" },
  ],

  ar: [
    { text: "كن أنت التغيير الذي تريد أن تراه في العالم.", author: "غاندي" },
    { text: "الحياة قصيرة، فاجعلها حلوة.", author: "مجهول" },
    { text: "ما لا يقتلك يزيدك قوة.", author: "فريدريك نيتشه" },
    { text: "أعظم انتصاراتك هي تلك التي تحققها على نفسك.", author: "أفلاطون" },
    { text: "النجاح هو أن تنتقل من فشل إلى فشل دون أن تفقد حماسك.", author: "ونستون تشرشل" },
    { text: "إذا كان لديك حلم، فعليك حمايته.", author: "ويل سميث" },
    { text: "الأمل آخر ما يموت في قلب الإنسان.", author: "مجهول" },
    { text: "ابتسم في وجه الحياة، تبتسم لك.", author: "مجهول" },
    { text: "أجمل ما في الحياة أن تكون سبباً في سعادة الآخرين.", author: "مجهول" },
    { text: "لا تنتظر الفرصة بل اصنعها.", author: "جورج برنارد شو" },
    { text: "العقل السليم في الجسم السليم.", author: "حكمة عربية" },
    { text: "من جدّ وجد، ومن زرع حصد.", author: "مثل عربي" },
    { text: "الصبر مفتاح الفرج.", author: "حكمة عربية" },
    { text: "أنت أقوى مما تظن.", author: "كريستوفر روبن" },
    { text: "كل يوم هو فرصة جديدة لتكون أفضل.", author: "مجهول" },
    { text: "السعادة ليست وجهة، بل طريقة للسفر.", author: "مارغريت لي رانبيك" },
    { text: "احلم كأنك ستعيش للأبد، وعش كأنك ستموت اليوم.", author: "جيمس دين" },
    { text: "العمل الجاد يتفوق على الموهبة عندما لا تعمل الموهبة بجد.", author: "تيم نوتك" },
    { text: "لا تخف من البطء، بل خف من التوقف.", author: "مثل صيني" },
    { text: "الفشل هو فرصة للبدء من جديد بشكل أكثر ذكاءً.", author: "هنري فورد" },
    { text: "كن لطيفاً، فكل شخص تقابله يخوض معركة لا تعلم عنها شيئاً.", author: "أفلاطون" },
    { text: "السماء ليست الحد، إنها مجرد البداية.", author: "مجهول" },
    { text: "الحياة جميلة لمن يعرف كيف يعيشها.", author: "مجهول" },
    { text: "لا تقارن نفسك بالآخرين، قارنها بمن كنت بالأمس.", author: "جوردان بيترسون" },
    { text: "العلم نور والجهل ظلام.", author: "حكمة عربية" },
    { text: "إن مع العسر يسراً.", author: "القرآن الكريم" },
    { text: "خير الناس أنفعهم للناس.", author: "حديث شريف" },
    { text: "لا تيأس فإن اليأس كفر، لعل الله يحدث بعد ذلك أمراً.", author: "علي بن أبي طالب" },
    { text: "الكلمة الطيبة صدقة.", author: "حديث شريف" },
    { text: "العاقل من وعظته التجارب.", author: "حكمة عربية" },
    { text: "من سار على الدرب وصل.", author: "مثل عربي" },
    { text: "كن كالشمس تنير ولا تحرق.", author: "مجهول" },
    { text: "الإيمان نصف الصبر، واليقين هو الإيمان كله.", author: "مجهول" },
    { text: "إذا أردت أن تعرف قيمة شخص، انظر كيف يعامل من هم أقل منه.", author: "مجهول" },
    { text: "النية الصادقة تفتح أبواباً لا يفتحها المفتاح.", author: "مجهول" },
  ],

  es: [
    { text: "La vida es lo que pasa mientras estás ocupado haciendo otros planes.", author: "John Lennon" },
    { text: "El éxito no es la clave de la felicidad. La felicidad es la clave del éxito.", author: "Albert Schweitzer" },
    { text: "Lo único imposible es aquello que no intentas.", author: "Anónimo" },
    { text: "No esperes el momento perfecto, toma el momento y hazlo perfecto.", author: "Anónimo" },
    { text: "La vida es 10% lo que te ocurre y 90% cómo reaccionas a ello.", author: "Charles R. Swindoll" },
    { text: "Cree que puedes y ya estarás a medio camino.", author: "Theodore Roosevelt" },
    { text: "La mejor manera de predecir el futuro es crearlo.", author: "Peter Drucker" },
    { text: "El que se enoja, pierde.", author: "Proverbio español" },
    { text: "No hay mal que por bien no venga.", author: "Proverbio español" },
    { text: "Las personas más felices no tienen lo mejor de todo, hacen lo mejor de todo.", author: "Anónimo" },
    { text: "Sé tú mismo, los demás puestos están ocupados.", author: "Oscar Wilde" },
    { text: "Lo que no te mata, te hace más fuerte.", author: "Friedrich Nietzsche" },
    { text: "El viaje de mil millas comienza con un solo paso.", author: "Lao Tzu" },
    { text: "Nunca es demasiado tarde para ser lo que podrías haber sido.", author: "George Eliot" },
    { text: "La felicidad no es algo hecho. Viene de tus propias acciones.", author: "Dalai Lama" },
    { text: "Si quieres algo que nunca has tenido, debes hacer algo que nunca has hecho.", author: "Thomas Jefferson" },
    { text: "El único modo de hacer un gran trabajo es amar lo que haces.", author: "Steve Jobs" },
    { text: "La paciencia es amarga, pero su fruto es dulce.", author: "Jean-Jacques Rousseau" },
    { text: "Aprende del ayer, vive el hoy, espera el mañana.", author: "Albert Einstein" },
    { text: "El que tiene un porqué para vivir, puede soportar casi cualquier cómo.", author: "Friedrich Nietzsche" },
    { text: "Los sueños no funcionan a menos que tú lo hagas.", author: "John C. Maxwell" },
    { text: "La vida es bella, solo hay que saber mirarla.", author: "Anónimo" },
    { text: "No cuentes los días, haz que los días cuenten.", author: "Muhammad Ali" },
    { text: "El secreto de salir adelante es comenzar.", author: "Mark Twain" },
    { text: "La esperanza es el sueño del hombre despierto.", author: "Aristóteles" },
    { text: "Quien no arriesga, no gana.", author: "Proverbio español" },
    { text: "A mal tiempo, buena cara.", author: "Proverbio español" },
    { text: "Caminante, no hay camino, se hace camino al andar.", author: "Antonio Machado" },
    { text: "Solo se vive una vez, pero si lo haces bien, una vez es suficiente.", author: "Mae West" },
    { text: "El obstáculo es el camino.", author: "Marco Aurelio" },
    { text: "Quien tiene salud tiene esperanza, y quien tiene esperanza lo tiene todo.", author: "Proverbio árabe" },
    { text: "La mente es como un paracaídas: solo funciona si se abre.", author: "Albert Einstein" },
    { text: "Si no luchas por lo que quieres, no llores por lo que pierdes.", author: "Anónimo" },
    { text: "El que ríe último, ríe mejor.", author: "Proverbio español" },
    { text: "El miedo a fallar mata más sueños que el fallo mismo.", author: "Suzy Kassem" },
  ],

  fr: [
    { text: "La vie est belle quand on sait l'apprécier.", author: "Anonyme" },
    { text: "Le seul moyen de faire du bon travail, c'est d'aimer ce que vous faites.", author: "Steve Jobs" },
    { text: "Ce qui ne nous tue pas nous rend plus fort.", author: "Friedrich Nietzsche" },
    { text: "La vie c'est comme une bicyclette, il faut avancer pour ne pas perdre l'équilibre.", author: "Albert Einstein" },
    { text: "Le bonheur n'est pas une destination, mais une manière de voyager.", author: "Margaret Lee Runbeck" },
    { text: "Croyez en vos rêves, ils se réaliseront peut-être. Croyez en vous, ils se réaliseront sûrement.", author: "Martin Luther King" },
    { text: "Là où il y a une volonté, il y a un chemin.", author: "Proverbe" },
    { text: "Le succès, c'est tomber sept fois et se relever huit.", author: "Proverbe japonais" },
    { text: "On ne voit bien qu'avec le cœur. L'essentiel est invisible pour les yeux.", author: "Antoine de Saint-Exupéry" },
    { text: "La patience est la clé du bien-être.", author: "Proverbe" },
    { text: "Rien n'est impossible à celui qui essaie.", author: "Alexandre le Grand" },
    { text: "Le voyage de mille lieues commence par un seul pas.", author: "Lao Tseu" },
    { text: "Soyez vous-même, les autres sont déjà pris.", author: "Oscar Wilde" },
    { text: "Le futur appartient à ceux qui croient en la beauté de leurs rêves.", author: "Eleanor Roosevelt" },
    { text: "Sois le changement que tu veux voir dans le monde.", author: "Gandhi" },
    { text: "Apprends comme si tu devais vivre toujours, vis comme si tu devais mourir demain.", author: "Gandhi" },
    { text: "Le plus grand échec est de ne jamais avoir essayé.", author: "Anonyme" },
    { text: "Il n'y a pas de honte à préférer le bonheur.", author: "Albert Camus" },
    { text: "Le bonheur est parfois caché dans l'inconnu.", author: "Victor Hugo" },
    { text: "Vivre c'est naître à chaque instant.", author: "Erich Fromm" },
    { text: "Le temps est un grand maître, dit-on. Le malheur est qu'il tue ses élèves.", author: "Hector Berlioz" },
    { text: "Ne remets pas à demain ce que tu peux faire aujourd'hui.", author: "Benjamin Franklin" },
    { text: "L'avenir est entre les mains de ceux qui osent.", author: "Anonyme" },
    { text: "La meilleure façon de prédire l'avenir, c'est de le créer.", author: "Peter Drucker" },
    { text: "Le plus difficile c'est de se décider à agir, le reste n'est que de la ténacité.", author: "Amelia Earhart" },
    { text: "Après la pluie, le beau temps.", author: "Proverbe français" },
    { text: "Petit à petit, l'oiseau fait son nid.", author: "Proverbe français" },
    { text: "Qui veut, peut.", author: "Proverbe français" },
    { text: "L'imagination est plus importante que le savoir.", author: "Albert Einstein" },
    { text: "Le monde appartient à ceux qui se lèvent tôt.", author: "Proverbe français" },
    { text: "Vouloir, c'est pouvoir.", author: "Proverbe français" },
    { text: "Mieux vaut tard que jamais.", author: "Proverbe français" },
    { text: "Chaque jour est un cadeau, c'est pour cela qu'on l'appelle le présent.", author: "Anonyme" },
    { text: "La simplicité est la sophistication suprême.", author: "Léonard de Vinci" },
    { text: "La vie n'est pas juste de respirer, mais d'avoir de quoi couper le souffle.", author: "Maya Angelou" },
  ],
};

export const getLanguageMeta = (code) =>
  SUPPORTED_LANGUAGES.find((l) => l.code === code) ?? SUPPORTED_LANGUAGES[0];
